name: Layan Automation

on:
  schedule:
    - cron: '0 */12 * * *'  # كل 12 ساعة: في الساعة 00:00 و12:00 حسب توقيت UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run script
        run: npm start

      - name: Upload result artifact
        uses: actions/upload-artifact@v4
        with:
          name: result-log
          path: result.txt
